language: php

sudo: false

php:
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

install:
  - composer require satooshi/php-coveralls

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

after_success:
  - vendor/bin/coveralls -v