language: php

sudo: false

php:
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 5.6
    - php: 7

install:
  - composer require satooshi/php-coveralls

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

after_success:
  - vendor/bin/coveralls -v
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN