language: php

sudo: false

php:
  - 7.2.5
  - 7.3
  - hhvm

matrix:
  allow_failures:
    - php: 7.4
    - php: 8
    - php: hhvm

install:
  - composer require satooshi/php-coveralls

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

after_success:
  - vendor/bin/coveralls -v