language: php

sudo: false

php:
  - 7.1.27
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.1.27
    - php: 7.2
    - php: 7.3

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit