language: php

sudo: false

php:
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit